name: librando_tla2_midterm
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
 flutter:
    sdk: flutter
 flutter_hooks: ^0.20.5
 flutter_test:
   sdk: flutter

  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

